#!/usr/bin/env bash
set -euo pipefail

{
  echo "APP_STORE_CONNECT_API_KEY_ID=${APP_STORE_CONNECT_API_KEY_ID:-}"
  echo "APP_STORE_CONNECT_ISSUER_ID=${APP_STORE_CONNECT_ISSUER_ID:-}"
  echo "APP_STORE_CONNECT_API_KEY_P8_BASE64=${APP_STORE_CONNECT_API_KEY_P8_BASE64:-}"
} >> "$GITHUB_ENV"
