#!/usr/bin/env bash
set -euo pipefail

{
  echo "XWORKMATE_SIGN_IDENTITY=${XWORKMATE_SIGN_IDENTITY:-}"
  echo "APPLE_CERT_P12_BASE64=${APPLE_CERT_P12_BASE64:-}"
  echo "APPLE_CERT_PASSWORD=${APPLE_CERT_PASSWORD:-}"
  echo "APPLE_PROVISION_PROFILE_BASE64=${APPLE_PROVISION_PROFILE_BASE64:-}"
  echo "APPLE_MAC_PROVISION_PROFILE_BASE64=${APPLE_MAC_PROVISION_PROFILE_BASE64:-}"
  echo "APPLE_KEYCHAIN_PASSWORD=${APPLE_KEYCHAIN_PASSWORD:-}"
  echo "APPLE_EXPORT_METHOD=${APPLE_EXPORT_METHOD:-}"
  echo "WINDOWS_PFX_BASE64=${WINDOWS_PFX_BASE64:-}"
  echo "WINDOWS_PFX_PASSWORD=${WINDOWS_PFX_PASSWORD:-}"
  echo "WINDOWS_CODESIGN_SUBJECT=${WINDOWS_CODESIGN_SUBJECT:-}"
  echo "ANDROID_KEYSTORE_BASE64=${ANDROID_KEYSTORE_BASE64:-}"
  echo "ANDROID_KEYSTORE_PASSWORD=${ANDROID_KEYSTORE_PASSWORD:-}"
  echo "ANDROID_KEY_ALIAS=${ANDROID_KEY_ALIAS:-}"
  echo "ANDROID_KEY_PASSWORD=${ANDROID_KEY_PASSWORD:-}"
} >> "$GITHUB_ENV"
